version: "3.8"
name: opuskanban-frontend

services:  
  web:
    container_name: app
    build: .
    command: "npm run dev"
    ports:
      - 8001:8001
    restart: unless-stopped
    networks:
      - opuskanban-backend_opuskanbanbackend
    volumes:
      - /app/node_modules     # No copy the node_modules, this can br also ignore from .dockerignore file
      - .:/app                # Copy all files and folders to the docker container inside the app folder

networks:
  opuskanban-backend_opuskanbanbackend:
    external: true