version: "3.8"
name: opuskanban-frontend

services:  
  app:
    container_name: app
    build: .
    command: "npm run preview"
    ports:
      - 8001:8001
    restart: unless-stopped
    networks:
      - opuskanban-backend_opuskanbanbackend

networks:
  opuskanban-backend_opuskanbanbackend:
    external: true