name: OpusKanban React CI/CD


# Event actions on the git repo to trigger the workflow
on: 

  # Trigger the workflow on push
  push:
    branches:
      - "main"

  # Trigger the worflow on merging
  pull_request:
    branches:
      - "main"


jobs:
  
  deploy:
    # Define the runner used in the worflow, actual machine server that runs the jobs
    runs-on: ubuntu-latest

    steps:
      # Check out repo so our workflow can access it
      - name: Checkout Code 
        uses: actions/checkout@v3

      # Step-1 Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      # Step-2 Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # Step-3 Build the app
      - name: Build the app
        run: npm run 
        
      # Step-4 Run Test
      # - name: Run Test
      #   run: npm test